---
title: "Final Overcompensation Stats"
author: "Team Rabbit"
date: "2022-4-7"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
    theme: flatly
  word_document:
    toc: yes
description: |
  Results from overcompensation study 
editor_options:
  chunk_output_type: console
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, libraries, warning=FALSE, include=FALSE}
# load libraries
library(tidyverse)
library(here)
library(patchwork)
library(janitor)
library(knitr)
library(lme4)
library(nlme)
library(car)
```

```{r read in data, warning=FALSE, include=FALSE}
# read in the data
full.df <- read.csv(here("Data/Other/popeco/overcomp.csv")) %>%
  clean_names() %>%
  remove_empty(which = c("cols", "rows"))

# remove column at end 
full.df <- full.df %>%
  select(-i_hate_math_cut_at_this_height_on_the_plant)

# rename treatment
full.df <- full.df %>%
  rename(trt = treat)

# make stuff factors
full.df <- full.df %>%
  mutate(week = as.factor(week),
         trt = as.factor(trt))

# water content
full.df <- full.df %>%
  mutate(water_content_g = above_wet_bio_g - above_dry_bio_g)

full.df <- full.df %>%
  mutate(water_ratio = (above_wet_bio_g - above_dry_bio_g) / above_wet_bio_g)

# remove column at end
# test.df <- full.df %>%
#   dplyr::select(week)
```

```{r summary, message=FALSE, warning=FALSE, include=FALSE}
# summary file 
summary.df <- full.df %>%
  group_by(trt) %>%
  summarize(total_dry_biomass = sum(above_dry_bio_g, na.rm = TRUE),
            total_wet_biomass = sum(above_wet_bio_g, na.rm = TRUE),
            dry_error = sd(above_dry_bio_g, na.rm = TRUE),
            wet_error = sd(above_wet_bio_g, na.rm = TRUE))

# calculate se
summary.df <- summary.df %>%
  mutate(dry_se = dry_error / 5) %>%
  mutate(wet_se = wet_error / 5)

# plus and minus se
summary.df <- summary.df %>%
  mutate(dry_error_plus_se = total_dry_biomass + dry_se) %>%
  mutate(dry_error_minus_se = total_dry_biomass - dry_se) %>%
  mutate(wet_error_plus_se = total_wet_biomass + wet_se) %>%
  mutate(wet_error_minus_se = total_wet_biomass - wet_se)

# add water ratio with se
summary.df <- summary.df %>%
  mutate(water_ratio = (total_wet_biomass - total_dry_biomass) / total_wet_biomass) %>%
  mutate(water_sd = sd(water_ratio)) %>%
  mutate(water_se = water_sd / 5)

# plus and minus of se for water ratio
summary.df <- summary.df %>%
  mutate(water_error_plus_se = water_ratio + water_se) %>%
  mutate(water_error_minus_se = water_ratio - water_se) 

# remove crap values
wr_ab_zero.df <- full.df %>%
  filter(water_ratio > 0)
```

```{r, prelim plots, include = FALSE}
# # make some graphs
# 
# # above wet by time 
# above_wet_t.plot <- full.df %>%
#   filter(week != 5) %>%
#   ggplot(aes(x = week, y = above_wet_bio_g, color = trt)) +
#   stat_summary(
#     fun = mean, na.rm = TRUE, geom = "point", size = 4) +
#   stat_summary(
#     fun.data = mean_se, na.rm = TRUE, geom = "errorbar", width = .3,size=.7) +
#   theme_classic()
# 
# # above dry by time
# above_dry_t.plot <- full.df %>%
#   filter(week != 5) %>%
#     ggplot(aes(x = week, y = above_dry_bio_g, color = trt)) +
#   stat_summary(
#     fun = mean, na.rm = TRUE, geom = "point", size = 4) +
#   stat_summary(
#     fun.data = mean_se, na.rm = TRUE, geom = "errorbar", width = .3,size=.7) +
#   theme_classic()
# 
# # above wet by trt
# above_wet_trt.plot <- full.df %>%
#   filter(week != 5) %>%
#     ggplot(aes(x = trt, y = above_wet_bio_g, color = week)) +
#   stat_summary(
#     fun = mean, na.rm = TRUE, geom = "point", size = 4) +
#   stat_summary(
#     fun.data = mean_se, na.rm = TRUE, geom = "errorbar", width = .3,size=.7) +
#   theme_classic()
# 
# # above dry by trt
# above_dry_trt.plot <- full.df %>%
#   filter(week != 5) %>%
#     ggplot(aes(x = trt, y = above_dry_bio_g, color = week)) +
#   stat_summary(
#     fun = mean, na.rm = TRUE, geom = "point", size = 4) +
#   stat_summary(
#     fun.data = mean_se, na.rm = TRUE, geom = "errorbar", width = .3,size=.7) +
#   theme_classic()
# 
# # water content
# water_content.plot <- full.df %>%
#     ggplot(aes(x = trt, y = water_content_g, color = week)) +
#   stat_summary(
#     fun = mean, na.rm = TRUE, geom = "point", size = 4) +
#   stat_summary(
#     fun.data = mean_se, na.rm = TRUE, geom = "errorbar", width = .3,size=.7) +
#   theme_classic()
# water_content.plot
# 
# # water ratio plot
# water_ratio.plot <- full.df %>%
#   filter(week != 5) %>%
#     ggplot(aes(x = trt, y = water_ratio, color = week)) +
#   stat_summary(
#     fun = mean, na.rm = TRUE, geom = "point", size = 4) +
#   stat_summary(
#     fun.data = mean_se, na.rm = TRUE, geom = "errorbar", width = .3,size=.7) +
#   theme_classic()
# 
# # test ratio plot
# test_ratio.plot <- full.df %>%
#   filter(week != 5) %>%
#     ggplot(aes(x = trt, y = test_ratio, color = week)) +
#   stat_summary(
#     fun = mean, na.rm = TRUE, geom = "point", size = 4) +
#   stat_summary(
#     fun.data = mean_se, na.rm = TRUE, geom = "errorbar", width = .3,size=.7) +
#   theme_classic()
# 
# above_wet_t.plot + above_dry_t.plot + above_wet_trt.plot + above_dry_trt.plot + water_content.plot + water_ratio.plot +
#   plot_layout(guides = "collect", ncol = 3)
# 
# water_content.plot + water_ratio.plot + test_ratio.plot + plot_layout(guides = "collect")
```

# Final plots
```{r, final plot code, include = FALSE}

# totals plot
total_dry_biomass.plot <- full.df %>%
  ggplot(aes(x= trt, y = above_dry_bio_g)) +
  stat_summary(
    fun = sum, na.rm = TRUE, geom = "point", size = 4) +
    labs(x = "Treatment", y = "Total Dry Abovegound Biomass (g)") +
  expand_limits(y = 0) +
  annotate("text", x = "0", y = 1, label = "B", size = 7) +
  annotate("text", x = "25", y = 1, label = "C", size = 7) +
  annotate("text", x = "50", y = 1, label = "B", size = 7) +
  annotate("text", x = "75", y = 1, label = "B", size = 7) +
  annotate("text", x = "100", y = 1, label = "A", size = 7) +
  annotate("text", x = "0", y = 32, label = "2", size = 7) +
  theme_classic()

# water ratio plot
# water_ratio.plot <- summary.df %>%
#   ggplot(aes(x = trt, y = water_ratio)) +
#   geom_point() +
#   geom_errorbar(aes(ymin = water_error_minus_se, ymax = water_error_plus_se),
#                 stat = "identity", width = 0.2) +
#   labs(x = "Treatment", y = "Total Proportion of Weight in Water") +
#   annotate("text", x = "0", y = 0.65, label = "A", size = 7) +
#   annotate("text", x = "25", y = 0.65, label = "A", size = 7) +
#   annotate("text", x = "50", y = 0.65, label = "A", size = 7) +
#   annotate("text", x = "75", y = 0.65, label = "A", size = 7) +
#   annotate("text", x = "100", y = 0.65, label = "B", size = 7) +
#   annotate("text", x = "0", y = 0.9, label = "1", size = 7) +
#   theme_classic()
# water_ratio.plot

water_ratio.plot <- wr_ab_zero.df %>%
  ggplot(aes(x = trt, y = water_ratio)) +
  stat_summary(
    fun = mean, na.rm = TRUE, geom = "point", size = 4) +
  stat_summary(
    fun.data = mean_se, na.rm = TRUE, geom = "errorbar", width = .3,size=.7) +
  labs(x = "Treatment", y = "Proportion of Weight in Water") +
  annotate("text", x = "0", y = 0.65, label = "A", size = 7) +
  annotate("text", x = "25", y = 0.65, label = "AB", size = 7) +
  annotate("text", x = "50", y = 0.65, label = "AB", size = 7) +
  annotate("text", x = "75", y = 0.65, label = "B", size = 7) +
  annotate("text", x = "100", y = 0.65, label = "C", size = 7) +
  annotate("text", x = "0", y = 0.9, label = "1", size = 7) +
  theme_classic()

```



```{r final plot, echo=FALSE, message=FALSE, warning=FALSE}
final.plot <- water_ratio.plot + total_dry_biomass.plot
final.plot
```

# Stats for Total Biomass
```{r, create summary for total biomass, include = FALSE}

# 100 treatments with 0s were put in as NAs so i went in and fixed that 

# rename pot to id
total_trt.df <- full.df %>%
  rename(id = pot_id)

# calculate sums per plot and treatment
total_trt.df <- total_trt.df %>%
  group_by(id, trt) %>%
  summarize(total_above_dry = sum(above_dry_bio_g, na.rm = TRUE))

# lmer doesn't work because there are as many treatments as n per treatment
# model.lm <- lmer(total_above_dry ~ trt + (1|id),
#                  data = total_trt.df,
#                  REML = TRUE)
# gonna use nlme and car for this then 
```


```{r model for total bio, echo=FALSE, message=FALSE, warning=FALSE}
rand.lm <- lme(total_above_dry ~ trt,
               random = ~ 1|id,
               data = total_trt.df, 
               method = "REML")

norand.lm <- gls(total_above_dry ~ trt,
                 data = total_trt.df, 
                 method = "REML")

# check AIC, no rand has lower AIC
anova(rand.lm, norand.lm)

# run anova
Anova(norand.lm, type = "3")
```


```{r totbio assumptions, echo=FALSE, message=FALSE, warning=FALSE}
# write it a simpler way to test the assumptions
one.lm <- lm(total_above_dry ~ trt, data = total_trt.df)

residuals <- resid(one.lm)
plot(fitted(one.lm), residuals)
qqnorm(residuals)
```

```{r totbio post f, echo=FALSE, message=FALSE, warning=FALSE}
# post F tests
library(emmeans)
emm.emm <- emmeans(one.lm, pairwise ~ trt, adjust = "bonferroni")

# plot
plot(emm.emm, comparisons = TRUE) + theme_classic()

emminteraction = emmeans(one.lm, pairwise ~ trt, adjust = "bonferroni", alpha = 0.5)
emminteraction$contrasts

library(multcomp)
cld(emm.emm, Letters = letters)
```

# Stats for Water Ratio
```{r water aic, echo=FALSE, message=FALSE, warning=FALSE}
# data frame for water
water.df <- full.df %>%
  rename(id = pot_id)

water.df <- water.df %>%
  dplyr::select(trt, id, water_ratio)

water.df <- water.df %>%
  na.omit(water_ratio)

water.df <- water.df %>%
  filter(water_ratio > 0)
# model selection
water_rand.lm <- lme(water_ratio ~ trt,
                     random = ~ 1|id,
                     data = water.df, 
                     method = "REML")

water_norand.lm <- gls(water_ratio ~ trt, 
                       data = water.df, 
                       method = "REML")
# random effect
anova(water_rand.lm, water_norand.lm)
```

```{r water anova, echo=FALSE, message=FALSE, warning=FALSE}
# model without random has lower aic so use that once
water_final.lm <- lm(water_ratio ~ trt, data = water.df)
# run anova
Anova(water_final.lm, type = "3")
```

```{r assumptions, echo=FALSE, message=FALSE, warning=FALSE}
# significant check assumptions
residuals <- resid(water_final.lm)
plot(fitted(water_final.lm), residuals)
qqnorm(residuals)
```

```{r post f water, echo=FALSE, message=FALSE, warning=FALSE}
# assumptions good run post f tests
water.emm <- emmeans(water_final.lm, pairwise ~ trt, adjust = "bonferroni")
# plot
plot(water.emm, comparisons = TRUE) + theme_classic()
# contrasts with emmeans
emminteraction = emmeans(water_final.lm, pairwise ~ trt, adjust = "bonferroni", alpha = 0.5)
emminteraction$contrasts
# groupings
cld(water.emm, Letters = letters)
```










